version: '3.7'
services:
  log-viewer-test:
    image: ${REGISTRY_HOST}/log-viewer-test:${CONTAINER_IMAGE}
    build:
      context: .
      dockerfile: ./test.Dockerfile
    volumes:
      - ./test/report:/app/test/report
