version: "3.7"

services:
  development:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - USER_UID=314587657
    user: "314587657:314587657"
    command: /bin/sh -c "while sleep 1000; do :; done"
    network_mode: "host"
    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - ../.:/workspace
